### ISSUE TITLE
Multiple Value Visualization - Visualization not taking up all fields from the explore

### ISSUE THREAD

**Issue by alex-burch** [looker/viz-multiple_value-marketplace#1]
When trying to have each measure use a corresponding table calculation as its comparison, whichever came last would override the others. It seems as if the visualization is not taking up all the fields from the explore.

**Comment by noahamac** [comment]
Hi @alex-burch 

Thank you for submitting this feedback. You might be interested in our most recent update to this visualization, which you can get by navigating to the "manage" page of the marketplace and pressing "update".

You can find the change here: https://github.com/looker/viz-multiple_value-marketplace/pull/5

The Multiple Value viz will now accept all field types: dimensions, measures, and table calculations.
