### ISSUE TITLE
Font does not match single value

### ISSUE THREAD

**Issue by zachwilner** [looker/viz-multiple_value-marketplace#2]
Is it possible to match the font and boldness of the single value tile so that when they are on the same dashboard things look consistent?

**Comment by noahamac** [comment]
We pushed an update to Multiple Value visualization this morning. This item was addressed directly by changing CSS styles to match the single value visualization. Thank you for your feedback! 

Navigate to the manage page of the marketplace to find an update. Thanks!

**Comment by zachwilner** [comment]
Looks great! Thanks so much!!!
