### ISSUE TITLE
Calculate with progress percentage does not show the value used to calculate the percent

### ISSUE THREAD

**Issue by zachwilner** [looker/viz-multiple_value-marketplace#3]
For some reason, the progress percentage comparison feature only shows the percentage and not the value of the comparison as well.

**Comment by noahamac** [comment]
@zachwilner We pushed an update to Multiple Value visualization this morning. If I understand your comment correctly, this update should address your feedback.

Navigate to the manage page of the marketplace to find an update. Thanks!

**Comment by zachwilner** [comment]
Thanks!! I will try it out
